name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  rust:
    uses: ./.github/workflows/rust.yml
  python:
    uses: ./.github/workflows/python.yml
  frontend:
    uses: ./.github/workflows/frontend.yml
