name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'

jobs:
  build-assets:
    uses: ./.github/workflows/build-assets.yml

  rust:
    needs: build-assets
    uses: ./.github/workflows/rust.yml

  python:
    needs: build-assets
    uses: ./.github/workflows/python.yml
