name: Nix

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'wrappers/python/**'
      - 'flake.nix'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/nix.yml'

jobs:
  check-release:
    uses: ./.github/workflows/check-release.yml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: lokeshmohanty
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Rust CLI
        run: nix build .#expman -o result-cli

      - name: Build Python Package
        run: nix build .#python3Packages.expman-rs -o result-python

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nix-build-results
          path: |
            result-cli/bin/exp
            result-python/dist/*.whl
          retention-days: 1

  github-release:
    needs: [check-release, build]
    if: needs.check-release.outputs.should_release == 'true'
    uses: ./.github/workflows/github-release.yml
    with:
      version: ${{ needs.check-release.outputs.version }}
      artifact-pattern: "nix-build-results"
    secrets: inherit
