name: Rust CI

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@just
      - uses: Swatinem/rust-cache@v2
      - name: Download frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist
      - name: Check formatting
        run: just fmt-check
      - name: Install protobuf compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Run clippy
        run: just lint-rust
        env:
          EXPMAN_SKIP_FRONTEND_BUILD: "1"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest
      - uses: Swatinem/rust-cache@v2
      - name: Download frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist
      - name: Install protobuf compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Run tests
        run: just test-release
        env:
          EXPMAN_SKIP_FRONTEND_BUILD: "1"
